docker:
  image: yegor256/java8
assets:
  settings.xml: llorllale/home#assets/cactoos-matchers/settings.xml
  pubring.gpg: llorllale/home#assets/pubring.gpg
  secring.gpg: llorllale/home#assets/secring.gpg
env:
  MAVEN_OPTS: -Xmx1g
  JAVA_OPTS: -Xmx1g
install: |
  sudo gem install --no-rdoc --no-ri pdd
  sudo gem install --no-rdoc --no-ri xcop
architect:
- llorllale
merge:
  script: |
    pdd --file=/dev/null
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml
deploy:
  script: |
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pcactoos -Psonar -Pqulice -Psonatype --errors --settings ../settings.xml
